[project]
name = "lightspeed-stack"
version = "0.1.0"
description = "LLM tooling stack"
authors = []
requires-python = ">=3.11.1,<=3.12.10"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.32.1",
    "llama-stack>=0.2.7",
    "rich>=14.0.0",
]

[project.urls]
Homepage = "https://github.com/lightspeed-core/lightspeed-stack"
Issues = "https://github.com/lightspeed-core/lightspeed-stack/issues"

[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.0",
]

[tool.pdm.scripts]
start = "pdm run make run"
test-unit = "pdm run make test-unit"
test-integration = "pdm run make test-integration"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
addopts = [
    "--import-mode=importlib",
]
