[tool.ruff]

# description of all rules are available on https://docs.astral.sh/ruff/rules/
lint.select = ["D", "E", "F", "W", "C", "S", "I", "TCH", "SLOT", "RUF", "C90", "N", "YTT", "ASYNC", "TRIO"]

# we need to check 'mood' of all docstrings, this needs to be enabled explicitly
lint.extend-select = ["D401"]

lint.ignore = []

target-version = "py311"
lint.pydocstyle.convention = "google"
line-length = 100

[tool.coverage.report]
# unit tests fails if the total coverage measurement is under this threshold value
fail_under = 90

[tool.mypy]
disable_error_code = ["union-attr", "return-value", "arg-type", "import-untyped"]
ignore_missing_imports = true

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
]

[[tool.pdm.source]]
type = "find_links"
url = "https://download.pytorch.org/whl/cpu/torch_stable.html"
name = "torch"

[project]
name = "ols"
version = "0.1.0"
description = "OpenShift LightSpeed is an AI powered assistant that runs on OpenShift and provides answers to product questions using backend LLM services."
authors = []
dependencies = [
    "torch==2.3.0",
    "fastapi==0.110.3",
    "gradio==4.28.3",
    "langchain==0.1.16",
    "langchain-ibm==0.1.4",
    "llama-index==0.10.33",
    "llama-index-vector-stores-faiss==0.1.2",
    "llama-index-embeddings-huggingface==0.2.0",
    "uvicorn==0.29.0",
    "redis==5.0.4",
    "faiss-cpu==1.8.0",
    "sentence-transformers==2.7.0",
    "openai==1.25.0",
    "ibm-watson-machine-learning==1.0.356",
    "ibm-generative-ai==2.3.0",
    "langchain-openai==0.1.4",
    "pydantic==2.7.1",
    "setuptools==69.5.1",
    "prometheus-client==0.19.0",
    "kubernetes==29.0.0",
    "pytest-asyncio==0.23.6",
    "psycopg2-binary==2.9.9",
    "black==24.2.0",
    "httpx==0.26.0",
    "mypy==1.9.0",
    "pytest==8.1.1",
    "pytest-cov==5.0.0",
    "pytest_asyncio==0.23.6",
    "ruff==0.4.1",
    "types-requests==2.31.0"
]
requires-python = "==3.11.*"
readme = "README.md"
license = "LICENSE"

[tool.pdm.scripts]
start = "pdm run make run"
test = "pdm run make test"
test-unit = "pdm run make test-unit"
test-integration = "pdm run make test-integration"
test-e2e = "pdm run make test-e2e"
coverage-report = "pdm run make coverage-report"
