// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for Status.
const (
	Error   Status = "error"
	Fail    Status = "fail"
	Success Status = "success"
)

// Status defines model for status.
type Status string

// RawReview defines model for rawReview.
type RawReview struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty"`
	Review      string    `json:"review"`
	Score       int       `json:"score"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId"`
}

// RawReviews defines model for rawReviews.
type RawReviews struct {
	Reviews *[]RawReview `json:"reviews,omitempty"`
}

// RawReviewsRequest defines model for rawReviewsRequest.
type RawReviewsRequest struct {
	Data *RawReviews `json:"data,omitempty"`
}

// Recommendation defines model for recommendation.
type Recommendation struct {
	Id    string  `json:"id"`
	Title *string `json:"title,omitempty"`
}

// Recommendations defines model for recommendations.
type Recommendations struct {
	Recommendations *[]Recommendation `json:"recommendations,omitempty"`
}

// RecommendationsErrorResponse defines model for recommendationsErrorResponse.
type RecommendationsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// RecommendationsFailResponse defines model for recommendationsFailResponse.
type RecommendationsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// RecommendationsSuccessResponse defines model for recommendationsSuccessResponse.
type RecommendationsSuccessResponse struct {
	Data   Recommendations `json:"data"`
	Status Status          `json:"status"`
}

// Review defines model for review.
type Review struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Id          string    `json:"id"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty"`
	Review      string    `json:"review"`
	Score       int       `json:"score"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId"`
}

// Reviews defines model for reviews.
type Reviews struct {
	Reviews *[]Review `json:"reviews,omitempty"`
}

// ReviewsErrorResponse defines model for reviewsErrorResponse.
type ReviewsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// ReviewsFailResponse defines model for reviewsFailResponse.
type ReviewsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// ReviewsSuccessResponse defines model for reviewsSuccessResponse.
type ReviewsSuccessResponse struct {
	Data   Reviews `json:"data"`
	Status Status  `json:"status"`
}

// RecommendContentToContentParams defines parameters for RecommendContentToContent.
type RecommendContentToContentParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RecommendContentToUserParams defines parameters for RecommendContentToUser.
type RecommendContentToUserParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// IngestReviewsJSONRequestBody defines body for IngestReviews for application/json ContentType.
type IngestReviewsJSONRequestBody = RawReviewsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Recommend content to content
	// (GET /recommendations/content/{contentId}/content)
	RecommendContentToContent(w http.ResponseWriter, r *http.Request, contentId string, params RecommendContentToContentParams)
	// Recommend content to user
	// (GET /recommendations/users/{userId}/content)
	RecommendContentToUser(w http.ResponseWriter, r *http.Request, userId string, params RecommendContentToUserParams)
	// Ingest review data
	// (POST /reviews)
	IngestReviews(w http.ResponseWriter, r *http.Request)
	// Delete review data
	// (DELETE /reviews/{reviewId})
	DeleteReview(w http.ResponseWriter, r *http.Request, reviewId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Recommend content to content
// (GET /recommendations/content/{contentId}/content)
func (_ Unimplemented) RecommendContentToContent(w http.ResponseWriter, r *http.Request, contentId string, params RecommendContentToContentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Recommend content to user
// (GET /recommendations/users/{userId}/content)
func (_ Unimplemented) RecommendContentToUser(w http.ResponseWriter, r *http.Request, userId string, params RecommendContentToUserParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ingest review data
// (POST /reviews)
func (_ Unimplemented) IngestReviews(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete review data
// (DELETE /reviews/{reviewId})
func (_ Unimplemented) DeleteReview(w http.ResponseWriter, r *http.Request, reviewId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RecommendContentToContent operation middleware
func (siw *ServerInterfaceWrapper) RecommendContentToContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "contentId" -------------
	var contentId string

	err = runtime.BindStyledParameterWithOptions("simple", "contentId", chi.URLParam(r, "contentId"), &contentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RecommendContentToContentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecommendContentToContent(w, r, contentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecommendContentToUser operation middleware
func (siw *ServerInterfaceWrapper) RecommendContentToUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RecommendContentToUserParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecommendContentToUser(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestReviews operation middleware
func (siw *ServerInterfaceWrapper) IngestReviews(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestReviews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteReview operation middleware
func (siw *ServerInterfaceWrapper) DeleteReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId string

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", chi.URLParam(r, "reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteReview(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recommendations/content/{contentId}/content", wrapper.RecommendContentToContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recommendations/users/{userId}/content", wrapper.RecommendContentToUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews", wrapper.IngestReviews)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/reviews/{reviewId}", wrapper.DeleteReview)
	})

	return r
}

type RecommendContentToContentRequestObject struct {
	ContentId string `json:"contentId"`
	Params    RecommendContentToContentParams
}

type RecommendContentToContentResponseObject interface {
	VisitRecommendContentToContentResponse(w http.ResponseWriter) error
}

type RecommendContentToContent200JSONResponse RecommendationsSuccessResponse

func (response RecommendContentToContent200JSONResponse) VisitRecommendContentToContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToContent400JSONResponse RecommendationsFailResponse

func (response RecommendContentToContent400JSONResponse) VisitRecommendContentToContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToContent404JSONResponse RecommendationsFailResponse

func (response RecommendContentToContent404JSONResponse) VisitRecommendContentToContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToContent500JSONResponse RecommendationsErrorResponse

func (response RecommendContentToContent500JSONResponse) VisitRecommendContentToContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToUserRequestObject struct {
	UserId string `json:"userId"`
	Params RecommendContentToUserParams
}

type RecommendContentToUserResponseObject interface {
	VisitRecommendContentToUserResponse(w http.ResponseWriter) error
}

type RecommendContentToUser200JSONResponse RecommendationsSuccessResponse

func (response RecommendContentToUser200JSONResponse) VisitRecommendContentToUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToUser400JSONResponse RecommendationsFailResponse

func (response RecommendContentToUser400JSONResponse) VisitRecommendContentToUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToUser404JSONResponse RecommendationsFailResponse

func (response RecommendContentToUser404JSONResponse) VisitRecommendContentToUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RecommendContentToUser500JSONResponse RecommendationsErrorResponse

func (response RecommendContentToUser500JSONResponse) VisitRecommendContentToUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type IngestReviewsRequestObject struct {
	Body *IngestReviewsJSONRequestBody
}

type IngestReviewsResponseObject interface {
	VisitIngestReviewsResponse(w http.ResponseWriter) error
}

type IngestReviews201JSONResponse ReviewsSuccessResponse

func (response IngestReviews201JSONResponse) VisitIngestReviewsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type IngestReviews400JSONResponse ReviewsFailResponse

func (response IngestReviews400JSONResponse) VisitIngestReviewsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IngestReviews500JSONResponse ReviewsErrorResponse

func (response IngestReviews500JSONResponse) VisitIngestReviewsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteReviewRequestObject struct {
	ReviewId string `json:"reviewId"`
}

type DeleteReviewResponseObject interface {
	VisitDeleteReviewResponse(w http.ResponseWriter) error
}

type DeleteReview200JSONResponse ReviewsSuccessResponse

func (response DeleteReview200JSONResponse) VisitDeleteReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteReview400JSONResponse ReviewsFailResponse

func (response DeleteReview400JSONResponse) VisitDeleteReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteReview404JSONResponse ReviewsFailResponse

func (response DeleteReview404JSONResponse) VisitDeleteReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteReview500JSONResponse ReviewsErrorResponse

func (response DeleteReview500JSONResponse) VisitDeleteReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Recommend content to content
	// (GET /recommendations/content/{contentId}/content)
	RecommendContentToContent(ctx context.Context, request RecommendContentToContentRequestObject) (RecommendContentToContentResponseObject, error)
	// Recommend content to user
	// (GET /recommendations/users/{userId}/content)
	RecommendContentToUser(ctx context.Context, request RecommendContentToUserRequestObject) (RecommendContentToUserResponseObject, error)
	// Ingest review data
	// (POST /reviews)
	IngestReviews(ctx context.Context, request IngestReviewsRequestObject) (IngestReviewsResponseObject, error)
	// Delete review data
	// (DELETE /reviews/{reviewId})
	DeleteReview(ctx context.Context, request DeleteReviewRequestObject) (DeleteReviewResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RecommendContentToContent operation middleware
func (sh *strictHandler) RecommendContentToContent(w http.ResponseWriter, r *http.Request, contentId string, params RecommendContentToContentParams) {
	var request RecommendContentToContentRequestObject

	request.ContentId = contentId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecommendContentToContent(ctx, request.(RecommendContentToContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecommendContentToContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecommendContentToContentResponseObject); ok {
		if err := validResponse.VisitRecommendContentToContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecommendContentToUser operation middleware
func (sh *strictHandler) RecommendContentToUser(w http.ResponseWriter, r *http.Request, userId string, params RecommendContentToUserParams) {
	var request RecommendContentToUserRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecommendContentToUser(ctx, request.(RecommendContentToUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecommendContentToUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecommendContentToUserResponseObject); ok {
		if err := validResponse.VisitRecommendContentToUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestReviews operation middleware
func (sh *strictHandler) IngestReviews(w http.ResponseWriter, r *http.Request) {
	var request IngestReviewsRequestObject

	var body IngestReviewsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestReviews(ctx, request.(IngestReviewsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestReviews")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestReviewsResponseObject); ok {
		if err := validResponse.VisitIngestReviewsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteReview operation middleware
func (sh *strictHandler) DeleteReview(w http.ResponseWriter, r *http.Request, reviewId string) {
	var request DeleteReviewRequestObject

	request.ReviewId = reviewId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteReview(ctx, request.(DeleteReviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteReview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteReviewResponseObject); ok {
		if err := validResponse.VisitDeleteReviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
