// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package model

// Defines values for Status.
const (
	Error   Status = "error"
	Fail    Status = "fail"
	Success Status = "success"
)

// RawReview defines model for rawReview.
type RawReview struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId" validate:"required,uuid"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty" validate:"omitempty,datetime=2006-01-02"`
	Review      string    `json:"review" validate:"required"`
	Score       int       `json:"score" validate:"required"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId" validate:"required,uuid"`
}

// RawReviews defines model for rawReviews.
type RawReviews struct {
	Reviews *[]RawReview `json:"reviews,omitempty"`
}

// RawReviewsRequest defines model for rawReviewsRequest.
type RawReviewsRequest struct {
	Data *RawReviews `json:"data,omitempty"`
}

// Recommendation defines model for recommendation.
type Recommendation struct {
	Id    string  `json:"id"`
	Title *string `json:"title,omitempty"`
}

// Recommendations defines model for recommendations.
type Recommendations struct {
	Recommendations *[]Recommendation `json:"recommendations,omitempty"`
}

// RecommendationsErrorResponse defines model for recommendationsErrorResponse.
type RecommendationsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// RecommendationsFailResponse defines model for recommendationsFailResponse.
type RecommendationsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// RecommendationsSuccessResponse defines model for recommendationsSuccessResponse.
type RecommendationsSuccessResponse struct {
	Data   Recommendations `json:"data"`
	Status Status          `json:"status"`
}

// Review defines model for review.
type Review struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId" validate:"required,uuid"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Id          string    `json:"id"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty" validate:"omitempty,datetime=2006-01-02"`
	Review      string    `json:"review" validate:"required"`
	Score       int       `json:"score" validate:"required"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId" validate:"required,uuid"`
}

// Reviews defines model for reviews.
type Reviews struct {
	Reviews *[]Review `json:"reviews,omitempty"`
}

// ReviewsErrorResponse defines model for reviewsErrorResponse.
type ReviewsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// ReviewsFailResponse defines model for reviewsFailResponse.
type ReviewsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// ReviewsSuccessResponse defines model for reviewsSuccessResponse.
type ReviewsSuccessResponse struct {
	Data   Reviews `json:"data"`
	Status Status  `json:"status"`
}

// Status defines model for status.
type Status string

// RecommendContentToContentParams defines parameters for RecommendContentToContent.
type RecommendContentToContentParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RecommendContentToUserParams defines parameters for RecommendContentToUser.
type RecommendContentToUserParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// IngestReviewsJSONRequestBody defines body for IngestReviews for application/json ContentType.
type IngestReviewsJSONRequestBody = RawReviewsRequest
