// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Status.
const (
	Error   Status = "error"
	Fail    Status = "fail"
	Success Status = "success"
)

// RawReview defines model for rawReview.
type RawReview struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty"`
	Review      string    `json:"review"`
	Score       int       `json:"score"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId"`
}

// RawReviews defines model for rawReviews.
type RawReviews struct {
	Reviews *[]RawReview `json:"reviews,omitempty"`
}

// RawReviewsRequest defines model for rawReviewsRequest.
type RawReviewsRequest struct {
	Data *RawReviews `json:"data,omitempty"`
}

// Recommendation defines model for recommendation.
type Recommendation struct {
	Id    string  `json:"id"`
	Title *string `json:"title,omitempty"`
}

// Recommendations defines model for recommendations.
type Recommendations struct {
	Recommendations *[]Recommendation `json:"recommendations,omitempty"`
}

// RecommendationsErrorResponse defines model for recommendationsErrorResponse.
type RecommendationsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// RecommendationsFailResponse defines model for recommendationsFailResponse.
type RecommendationsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// RecommendationsSuccessResponse defines model for recommendationsSuccessResponse.
type RecommendationsSuccessResponse struct {
	Data   Recommendations `json:"data"`
	Status Status          `json:"status"`
}

// Review defines model for review.
type Review struct {
	Actors      *[]string `json:"actors,omitempty"`
	ContentId   string    `json:"contentId"`
	Description *string   `json:"description,omitempty"`
	Director    *string   `json:"director,omitempty"`
	Duration    *int      `json:"duration,omitempty"`
	Genres      *[]string `json:"genres,omitempty"`
	Id          string    `json:"id"`
	Origins     *[]string `json:"origins,omitempty"`
	Released    *string   `json:"released,omitempty"`
	Review      string    `json:"review"`
	Score       int       `json:"score"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
	UserId      string    `json:"userId"`
}

// Reviews defines model for reviews.
type Reviews struct {
	Reviews *[]Review `json:"reviews,omitempty"`
}

// ReviewsErrorResponse defines model for reviewsErrorResponse.
type ReviewsErrorResponse struct {
	Code    *int                    `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Status  Status                  `json:"status"`
}

// ReviewsFailResponse defines model for reviewsFailResponse.
type ReviewsFailResponse struct {
	Data   map[string]interface{} `json:"data"`
	Status Status                 `json:"status"`
}

// ReviewsSuccessResponse defines model for reviewsSuccessResponse.
type ReviewsSuccessResponse struct {
	Data   Reviews `json:"data"`
	Status Status  `json:"status"`
}

// Status defines model for status.
type Status string

// RecommendContentToContentParams defines parameters for RecommendContentToContent.
type RecommendContentToContentParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RecommendContentToUserParams defines parameters for RecommendContentToUser.
type RecommendContentToUserParams struct {
	// Limit Pagination limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// IngestReviewsJSONRequestBody defines body for IngestReviews for application/json ContentType.
type IngestReviewsJSONRequestBody = RawReviewsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Recommend content to content
	// (GET /recommendations/content/{contentId}/content)
	RecommendContentToContent(w http.ResponseWriter, r *http.Request, contentId string, params RecommendContentToContentParams)
	// Recommend content to user
	// (GET /recommendations/users/{userId}/content)
	RecommendContentToUser(w http.ResponseWriter, r *http.Request, userId string, params RecommendContentToUserParams)
	// Ingest review data
	// (POST /reviews)
	IngestReviews(w http.ResponseWriter, r *http.Request)
	// Delete review data
	// (DELETE /reviews/{reviewId})
	DeleteReview(w http.ResponseWriter, r *http.Request, reviewId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Recommend content to content
// (GET /recommendations/content/{contentId}/content)
func (_ Unimplemented) RecommendContentToContent(w http.ResponseWriter, r *http.Request, contentId string, params RecommendContentToContentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Recommend content to user
// (GET /recommendations/users/{userId}/content)
func (_ Unimplemented) RecommendContentToUser(w http.ResponseWriter, r *http.Request, userId string, params RecommendContentToUserParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ingest review data
// (POST /reviews)
func (_ Unimplemented) IngestReviews(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete review data
// (DELETE /reviews/{reviewId})
func (_ Unimplemented) DeleteReview(w http.ResponseWriter, r *http.Request, reviewId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RecommendContentToContent operation middleware
func (siw *ServerInterfaceWrapper) RecommendContentToContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "contentId" -------------
	var contentId string

	err = runtime.BindStyledParameterWithOptions("simple", "contentId", chi.URLParam(r, "contentId"), &contentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RecommendContentToContentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecommendContentToContent(w, r, contentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecommendContentToUser operation middleware
func (siw *ServerInterfaceWrapper) RecommendContentToUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RecommendContentToUserParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecommendContentToUser(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestReviews operation middleware
func (siw *ServerInterfaceWrapper) IngestReviews(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestReviews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteReview operation middleware
func (siw *ServerInterfaceWrapper) DeleteReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId string

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", chi.URLParam(r, "reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteReview(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recommendations/content/{contentId}/content", wrapper.RecommendContentToContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recommendations/users/{userId}/content", wrapper.RecommendContentToUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reviews", wrapper.IngestReviews)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/reviews/{reviewId}", wrapper.DeleteReview)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX2/bOBL/KgR7wP2BaUuWZFl5a5N24cNdt0jbh9s2DyNxZLMrkS5JOWsE+e4HUpb/",
	"Ko23l9wCiwJ5UCRyZjgzv9/M0He0UPVSSZTW0Is7aooF1uAfNdxe40rgrftnqdUStRXoP0FhlfZPwmLt",
	"H/A3qJeV+/yJfhA1uVZ5LqShA/pvpecgyRuNWIOkNwNq10ukF9RYLeSc3m9fgNawdv8XSlqUdsaPJWdR",
	"mkdRXrJgMgEWx2XKMshyxidJkIZ8nI7TgA5ompSYhZCyDPOCxcE4Y1nq1vIsgyDJonjKew3haAotllYo",
	"eaz6JanVSiCBXDWWzEHOjUVthv1yhEbno2MhlwstjFXLBWryVlUg6YC+0SB/JVegIVfS9otrNPTYNE3G",
	"wSALp8Fuj5AW56jdpjlKjQ8HiWuogQ4oamVFQQfULrSoKtRnRUhpMXfhfUj6x/cv6YBe/nKWMI0VgsGT",
	"aI+D8ZgFGQujD0Fw4f9+oQMaZlnGgpCFyd7rPj16m777UmdEI1TVmqD8otbIiV0IQ5TE/lCaQmk8kpEm",
	"g3HY63QL84edYhpRCI7U5VmBbZYNaKkFSm7O8pQVtjo2hv4skbyp8JaoFWpiF0gum+JXpf5qyFs0/RnV",
	"GNSn8BqXWcbLlLM0CR1uiowBIrBpjtOCp3kJmUuZcDKZ8jFM2SSKYxZHUwevLGVFNA2LJMmDaZD3aPUR",
	"+doI7SL9aQ/kW3O2IevcvhOi8i9YWB/VjpfMKTHp3YdtBP6isaQX9MVox3SjDc2Ndhx34uz7b6q+xq+N",
	"8+2JBRwsnK3VPKAGC1XXKPkW9Ic6xEngyiTOOY6B5SHELC7LgEEaRKzAkgdZOi0xz+mABklSJuEkYJOE",
	"RywOMGSQxCWLomk05TyOJoWLb5IhpAXGLIyShMUJTFjGy5DlSRRPMB5neTLtT9e+9JzJeaUaLVRjyCtw",
	"pMldWfiwQPKT4iXYBWo6oO+aakneiMIf+dHkEbw/Nw4815sgJwvOS5TDkJyXLYe6Xmut9DWapZIGTy0r",
	"FD92XRL0M3uXYycaazQG5icR+Cghr5BYRZxBjRQFWCS3wi6IE5WDcZx0qZqKE6kscciEwhKQBH+zqCVU",
	"xKBeiQL7KdKCbR514WbVcSQ3r3fGnxHXNyCqhz3ZuWfPBS1m6OyKCOOPuIJKcPLx4+xqSO/7ND7Nmbwp",
	"ZxzofVMUaMzjZzo/R83/5RRdgYWq+rn0jn6MqpIEgjBMQsbjsGRxFBQsL7KYQTqe5hhNYIyuhcMSokkQ",
	"TVgRFQWL42zKsiAMWTrNJ1DyaZQE4++libNrws32jE9Ra35PoWll/6CM/4UyvAv/DFThD/JEFLFpO57d",
	"6p14lE3ddr/+AK7jBVH5yUOrvmnDKROyVP5Q+wMZffHiBXF9wyHTdYlGCpAXn+U/yEzO0bhc5IRjhdZt",
	"cOf2qesWXHf7yaYJbRPdPz743fWo5rP8LFsL2jAQZ7txIFlW6xYfrgE3wqUT+fTP9yj5zd8W1i7NxWg0",
	"F3bR5MNC1SNVS2EFqyA3oy8GJf87MRYkB82Hn91YUIkCN3GWUDv/XF6SV/9h71+SeBiQq9evr1zjrCt6",
	"QTv5hUawYuWtV9IMlZ6PNnLMKF8zA6N4GIw4Ih+i3OvY6DVi9ZNS5Zq8fDejA7pCbVqfh8NgGPiRb4kS",
	"loJe0GgYDh1HL8EufIiPS89o47bR3bbJv+/eufVztKfB3Trd7Hsdtv+YJRaiFMhJvvZO3somjo44UZLA",
	"CkTlmWsv4kPqjW9HaDf07FRdtiI+qM2DP5SGGt1o78ng0MbZFVHl1qJSq5rcLkTRBv3ICQQ0kho4Ov3C",
	"7Xb+ooMunPvzzw5bVjc42FzDHJNyzHkYRMBZEvOExTkfM8gCZEkKRTLGYJxk0FsTj4/xDuZCttipRC1s",
	"Z+DXBvV6Z2H3rdeacV+h+aYqVZYGH9K1/dirLOwta46NOyD6PBwHQVsXt5kGy2XlapdQcvTFtMPUTsPv",
	"6KaO6dez1OFRN0vKpqrWu2TALYk4EMXPZ+FBpes1z2lC7jFBSqVrsK7GCekrXGtd/EdZ91YR0xSLHbZU",
	"I71NyfN57LC96jFqJvdaGdTEVyyiiqLRDqxug2nqGvR6n1R6igrtboY+nUygN07KCYH6YjO6a+9Fvp87",
	"3f5T4mylPgFrfjR+dD+DMr0hpdLfT5d7V0Q/uPIHV/7gykUHqj8FUTYtlTzGkrtZXJkeHtx0/hJvD6hs",
	"19DvcY1doPSEQxoj5Lz9GeCbBNhK765uWyZCY18pvn46z59cMd/ft9PXAXbDJwx173j5GGaF9wVysjdS",
	"Pi1gT8f3c4GqdBfHFVQNtuHeg27y9HY+LUI2abyXjAfQaB1+AInRXfsw4/ctKtzYe4qPK//+IM2Jxgpc",
	"IK3yZXkuVijJ7Oo0/dvN190vNGdU/Y0auwBLbkVVkRw3Ezl/oMp3pzi7zqdRlGdlMGVpGHAWQ16yLCoz",
	"lkZJhHycxxj0/VbxzOXwuyC18QzZXRT+4YB6zpJ3ljldqdtk0jMVu2eA8NXJxVM/hN0mL64PRf9SBVQL",
	"ZSzhuMJKLWt/EeLXH1z+XIxGVbf24m6ptL0f3bn+/h3YxT0d0BVo4Tp8n+vdh5YfSmgqSy8oLMVoFTrn",
	"uv2H36bBNHAuudme4djUzUzQHRglXyohrTmGtqGnfe9u78G1Xq+Mo584bu7/GwAA//+aqs0YwiIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
