name: List outdated packages

on:
  - push
  - pull_request

jobs:
  list_outdated_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Check Python version
        run: python --version
      - name: Install pip-tools
        run: pip install --user pip-tools
      - name: Install pip-outdated
        run: pip install pip-outdated
      - name: Check lip-compile version
        run: pip-compile --version
      - name: Generate requirements.txt file
        run: pip-compile -v --generate-hashes pyproject.toml
      - name: List requirements.txt file
        run: cat requirements.txt
      #- name: List outdated packages
      #  run: TERM=xterm;pip-outdated requirements.txt
