name: List outdated packages

on:
  - push
  - pull_request

jobs:
  list_outdated_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: Generate requirements.txt file
        run: pip-compile -v --generate-hashes pyproject.toml
      - name: List outdated packages
        run: pip list --outdated

